/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package payroll;

import java.awt.Color;
import java.awt.event.KeyEvent;
import java.io.File;
import java.io.FileOutputStream;
import java.io.IOException;
import java.text.MessageFormat;
import java.util.List;
import java.util.Set;
import java.util.TreeMap;
import java.util.logging.Level;
import javax.swing.BorderFactory;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.border.Border;
import javax.swing.table.DefaultTableModel;
import org.apache.poi.ss.usermodel.Cell;
import org.apache.poi.xssf.usermodel.XSSFRow;
import org.apache.poi.xssf.usermodel.XSSFSheet;
import org.apache.poi.xssf.usermodel.XSSFWorkbook;
import static payroll.Payroll.searchList;

/**
 *
 * @author mzohaib
 */
public class Emp_Salary_Table extends javax.swing.JFrame {

    /**
     * Creates new form Emp_Salary_Table
     */
    
    DB_CRUD db_crud;
    DefaultTableModel model;
    private List<EmployeeSalary> empSalaryList;
    
    public Emp_Salary_Table() {
        initComponents();
        db_crud=DB_CRUD.getInstance();
        model=(DefaultTableModel) jTable1.getModel();
        empSalaryList=null;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton_print = new javax.swing.JButton();
        jLabel_close = new javax.swing.JLabel();
        jLabel_minimize = new javax.swing.JLabel();
        jButton_generateExcel = new javax.swing.JButton();
        jBackButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jTextField_editPfund = new javax.swing.JTextField();
        jTextField_editItax = new javax.swing.JTextField();
        jTextField_editAdvSal = new javax.swing.JTextField();
        jTextField_editPFloan = new javax.swing.JTextField();
        jTextField_editPersLoan = new javax.swing.JTextField();
        jTextField_editMessDed = new javax.swing.JTextField();
        jTextField_editEOBI = new javax.swing.JTextField();
        jTextField_editOtherDed = new javax.swing.JTextField();
        jButton_saveEditedInfo = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField_empID = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton_print.setText("Print");
        jButton_print.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_printActionPerformed(evt);
            }
        });

        jLabel_close.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabel_close.setText(" X");
        jLabel_close.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel_close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_closeMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel_closeMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel_closeMouseEntered(evt);
            }
        });

        jLabel_minimize.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabel_minimize.setText(" -");
        jLabel_minimize.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel_minimize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_minimizeMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel_minimizeMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel_minimizeMouseEntered(evt);
            }
        });

        jButton_generateExcel.setText("Save as Excel File");
        jButton_generateExcel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_generateExcelActionPerformed(evt);
            }
        });

        jBackButton.setBackground(new java.awt.Color(204, 204, 204));
        jBackButton.setForeground(new java.awt.Color(102, 102, 255));
        jBackButton.setText("Back");
        jBackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBackButtonActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Name", "Salary Date", "Gross Salary", "T.Work Mins", "Earned.Sal", "P-Fund", "Itax", "Adv.Salary", "PF Loan", "Pers.Loan", "Mess Ded", "EOBI", "Other Ded", "Net Salary"
            }
        ));
        jTable1.setSize(new java.awt.Dimension(371, 64));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 102, 255));
        jLabel1.setText("EMPLOYEE SALARY DATA");

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));

        jTextField_editPfund.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_editPfundActionPerformed(evt);
            }
        });

        jTextField_editPersLoan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_editPersLoanActionPerformed(evt);
            }
        });

        jTextField_editMessDed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_editMessDedActionPerformed(evt);
            }
        });

        jTextField_editOtherDed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_editOtherDedActionPerformed(evt);
            }
        });

        jButton_saveEditedInfo.setForeground(new java.awt.Color(102, 102, 255));
        jButton_saveEditedInfo.setText("Save");
        jButton_saveEditedInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_saveEditedInfoActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Lucida Grande", 0, 16)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(102, 102, 255));
        jLabel3.setText("P-Fund");

        jLabel4.setFont(new java.awt.Font("Lucida Grande", 0, 16)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(102, 102, 255));
        jLabel4.setText("Itax");

        jLabel5.setFont(new java.awt.Font("Lucida Grande", 0, 16)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(102, 102, 255));
        jLabel5.setText("PfLoan");

        jLabel6.setFont(new java.awt.Font("Lucida Grande", 0, 16)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(102, 102, 255));
        jLabel6.setText("Adv.Sal");

        jLabel7.setFont(new java.awt.Font("Lucida Grande", 0, 16)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(102, 102, 255));
        jLabel7.setText("Pers-Loan");

        jLabel8.setFont(new java.awt.Font("Lucida Grande", 0, 16)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(102, 102, 255));
        jLabel8.setText("Mess-Ded");

        jLabel9.setFont(new java.awt.Font("Lucida Grande", 0, 16)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(102, 102, 255));
        jLabel9.setText("EOBI");

        jLabel10.setFont(new java.awt.Font("Lucida Grande", 0, 16)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(102, 102, 255));
        jLabel10.setText("Other-Ded");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField_editPfund, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField_editItax, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextField_editAdvSal, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextField_editPFloan, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jTextField_editPersLoan, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(jTextField_editMessDed, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jTextField_editEOBI, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addGap(43, 43, 43)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTextField_editOtherDed))
                .addGap(36, 36, 36)
                .addComponent(jButton_saveEditedInfo)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(jLabel9)
                            .addComponent(jLabel8)
                            .addComponent(jLabel7)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField_editPfund, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField_editItax, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField_editAdvSal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField_editPFloan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField_editPersLoan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField_editMessDed, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField_editEOBI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField_editOtherDed, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(15, 15, 15))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton_saveEditedInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(16, 16, 16))))
        );

        jLabel2.setFont(new java.awt.Font("Lucida Grande", 0, 16)); // NOI18N
        jLabel2.setText("Enter Employee ID:");

        jTextField_empID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_empIDActionPerformed(evt);
            }
        });
        jTextField_empID.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField_empIDKeyPressed(evt);
            }
        });

        jLabel14.setForeground(new java.awt.Color(102, 102, 255));
        jLabel14.setText("Developed By Mohammad Zohaib Abbas ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jButton_print, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextField_empID, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButton_generateExcel))
                                .addGap(45, 45, 45)
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jBackButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addGap(383, 383, 383)
                        .addComponent(jLabel_minimize, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel_close, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(19, 19, 19))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel14)
                .addGap(478, 478, 478))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel_close)
                        .addComponent(jLabel_minimize)
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jBackButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton_print, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton_generateExcel, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jTextField_empID))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 553, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_printActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_printActionPerformed
        // TODO add your handling code here:
        int count=model.getRowCount();
            if(count<=0){ // if table is not empty
                JOptionPane.showMessageDialog(this, "CAN NOT Print Empty Table!");
            }
            else{
                MessageFormat header=new MessageFormat("SALARY SHEET");
                MessageFormat footer=new MessageFormat("Page{0,number,integer}");
                try{
                    jTable1.print(JTable.PrintMode.NORMAL,header,footer);
                }catch(java.awt.print.PrinterException e){
                    JOptionPane.showMessageDialog(this, "Error Occured While Printing!");
                    System.err.format("Cannot Print %s%n", e.getMessage());
                }
            }
        
    }//GEN-LAST:event_jButton_printActionPerformed

    private void jLabel_closeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_closeMouseClicked
        System.exit(0);
    }//GEN-LAST:event_jLabel_closeMouseClicked

    private void jLabel_closeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_closeMouseExited
        Border label_border=BorderFactory.createMatteBorder(1,1,1,1, Color.black);
        jLabel_close.setBorder(label_border);
        jLabel_close.setForeground(Color.black);
    }//GEN-LAST:event_jLabel_closeMouseExited

    private void jLabel_closeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_closeMouseEntered
        Border label_border=BorderFactory.createMatteBorder(1,1,1,1, Color.white);
        jLabel_close.setBorder(label_border);
        jLabel_close.setForeground(Color.white);
    }//GEN-LAST:event_jLabel_closeMouseEntered

    private void jLabel_minimizeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_minimizeMouseClicked
        this.setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_jLabel_minimizeMouseClicked

    private void jLabel_minimizeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_minimizeMouseExited
        Border label_border=BorderFactory.createMatteBorder(1,1,1,1, Color.black);
        jLabel_minimize.setBorder(label_border);
        jLabel_minimize.setForeground(Color.black);
    }//GEN-LAST:event_jLabel_minimizeMouseExited

    private void jLabel_minimizeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_minimizeMouseEntered
        Border label_border=BorderFactory.createMatteBorder(1,1,1,1, Color.white);
        jLabel_minimize.setBorder(label_border);
        jLabel_minimize.setForeground(Color.white);
    }//GEN-LAST:event_jLabel_minimizeMouseEntered

    private String getCellValue(int x,int y){
        if(model.getValueAt(x,y)!=null){
            return model.getValueAt(x,y).toString();
        }
        return null;
    }
    
    private void jButton_generateExcelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_generateExcelActionPerformed
        // TODO add your handling code here:
        int noOfRows=model.getRowCount();

        int salaryListSize=empSalaryList.size();

        if(noOfRows>0&&salaryListSize<=noOfRows){

            XSSFWorkbook wb=new XSSFWorkbook();
            XSSFSheet ws=wb.createSheet();

            TreeMap<String,Object[]> data=new TreeMap<>();
            int i=-1;
            data.put(Integer.toString(i),new Object[]{"ID","Name","Salary Date","Gross Salary","Total Work Mins","Earned Salary","P-Fund","Itax","Adv.Sal","PF Loan","Personal Loan","Mess Ded","EOBI","Other Ded","Net Salary"});
            i++;
            for(;i<noOfRows;i++){
                try{
                  if(getCellValue(i, 0)!=null){
                    data.put(Integer.toString(i),new Object[]{getCellValue(i, 0),getCellValue(i, 1),getCellValue(i, 2),getCellValue(i, 3),getCellValue(i, 4),getCellValue(i, 5),getCellValue(i, 6),getCellValue(i, 7),getCellValue(i, 8),getCellValue(i, 9),getCellValue(i, 10),getCellValue(i, 11),getCellValue(i, 12),getCellValue(i, 13),getCellValue(i, 14)});
                  }
                }
                catch(NullPointerException ne){
                    System.out.println("Null Pointer Exception");
                }
            }

            Set<String> ids=data.keySet();
            XSSFRow row;
            int rowID=0;

            for(String key: ids){
                row=ws.createRow(rowID++);

                Object[] values=data.get(key);

                int cellID=0;
                for(Object o:values){
                    Cell cell=row.createCell(cellID++);
                    cell.setCellValue(o.toString());
                }
            }

            try{
                FileOutputStream fos=new FileOutputStream(new File("EmployeeSalarySheet.xlsx"));
                wb.write(fos);
                fos.close();
            } catch (IOException ex) {
                JOptionPane.showMessageDialog(this, "Error Generating Excel File!");
                java.util.logging.Logger.getLogger(Salary_Sheet_Table.class.getName()).log(Level.SEVERE, null, ex);
            }

            JOptionPane.showMessageDialog(this, "Excel File Generated Successfully!");
        }
        else{
            JOptionPane.showMessageDialog(this, "Can Not Generate Empty Excel File!");
        }

    }//GEN-LAST:event_jButton_generateExcelActionPerformed

    private void jBackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBackButtonActionPerformed
        this.setVisible(false);
        Payroll.getHomePage().setVisible(true);
    }//GEN-LAST:event_jBackButtonActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        try{
            int i=jTable1.getSelectedRow();

            jTextField_editPfund.setText(model.getValueAt(i,6).toString());
            jTextField_editItax.setText(model.getValueAt(i,7).toString());
            jTextField_editAdvSal.setText(model.getValueAt(i,8).toString());
            jTextField_editPFloan.setText(model.getValueAt(i,9).toString());
            jTextField_editPersLoan.setText(model.getValueAt(i,10).toString());
            jTextField_editMessDed.setText(model.getValueAt(i,11).toString());
            jTextField_editEOBI.setText(model.getValueAt(i,12).toString());
            jTextField_editOtherDed.setText(model.getValueAt(i,13).toString());
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(this, "Empty Row Selected!");
        }
    }//GEN-LAST:event_jTable1MouseClicked

    private void jTextField_editPfundActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_editPfundActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_editPfundActionPerformed

    private void jTextField_editPersLoanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_editPersLoanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_editPersLoanActionPerformed

    private void jTextField_editMessDedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_editMessDedActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_editMessDedActionPerformed

    private void jTextField_editOtherDedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_editOtherDedActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_editOtherDedActionPerformed

    private void jButton_saveEditedInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_saveEditedInfoActionPerformed
        try{
            int i=jTable1.getSelectedRow();
            int id=(int) model.getValueAt(i,0);
            String date=model.getValueAt(i,2).toString();
            EmployeeInformation emp=db_crud.searchDB(id);
            boolean flag=false;

            int pfund,itax,advSal,pfLoan,PersLoan,MessDed,Eobi,OtherDed;

            try{
                pfund=Integer.parseInt(jTextField_editPfund.getText());
                itax=Integer.parseInt(jTextField_editItax.getText());
                advSal=Integer.parseInt(jTextField_editAdvSal.getText());
                pfLoan=Integer.parseInt(jTextField_editPFloan.getText());
                PersLoan=Integer.parseInt(jTextField_editPersLoan.getText());
                MessDed=Integer.parseInt(jTextField_editMessDed.getText());
                Eobi=Integer.parseInt(jTextField_editEOBI.getText());
                OtherDed=Integer.parseInt(jTextField_editOtherDed.getText());
            }
            catch(NumberFormatException e){
                JOptionPane.showMessageDialog(this, "Error Detected in Deduction Fields! Please recheck your entered values.");
                pfund=0;
                itax=0;
                advSal=0;
                pfLoan=0;
                PersLoan=0;
                MessDed=0;
                Eobi=0;
                OtherDed=0;
                flag=true;
            }

            if(!flag){
                emp.setP_Fund(pfund);
                emp.setItax(itax);
                emp.setAdvSal(advSal);
                emp.setPF_Loan(pfLoan);
                emp.setPersonalLoan(PersLoan);
                emp.setMessDed(MessDed);
                emp.setEOBI(Eobi);
                emp.setOtherDed(OtherDed);
                boolean check=db_crud.updateDB(emp);
                if(check){
                    //JOptionPane.showMessageDialog(this, "Saved Successfully!");
                    EmployeeSalary emp_sal=db_crud.searchEmployeeSalaryDB(id,date);
                    int new_ded_sum=0;
                    new_ded_sum=new_ded_sum+pfund+itax+advSal+pfLoan+PersLoan+MessDed+Eobi+OtherDed;
                    int new_net_salary=emp_sal.getEarnedSalary()-new_ded_sum;
                    emp_sal.setNetSalary(new_net_salary);
                    boolean check2=db_crud.updateEmployeeSalaryDB(emp_sal);
                    if(check2){ // if information updated in both tables of the database successfully
                        JOptionPane.showMessageDialog(this, "Saved Successfully!");
                        model.setValueAt(emp_sal.getNetSalary(),i,14);

                        model.setValueAt(pfund,i,6);
                        model.setValueAt(itax,i,7);
                        model.setValueAt(advSal,i,8);
                        model.setValueAt(pfLoan,i,9);
                        model.setValueAt(PersLoan,i,10);
                        model.setValueAt(MessDed,i,11);
                        model.setValueAt(Eobi,i,12);
                        model.setValueAt(OtherDed,i,13);
                    }
                    else{
                        JOptionPane.showMessageDialog(this, "Update Failed!");
                    }
                }
                else{
                    JOptionPane.showMessageDialog(this, "Update Failed!");
                }
            }

        }
        catch(Exception e){
            JOptionPane.showMessageDialog(this, "Error Occured While Saving! Please recheck your input values.");
        }
    }//GEN-LAST:event_jButton_saveEditedInfoActionPerformed

    private void jTextField_empIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_empIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_empIDActionPerformed

    private void jTextField_empIDKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_empIDKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            model.setRowCount(0);
            if(jTextField_empID.getText().trim().length()==0||jTextField_empID.getText()==null){
                JOptionPane.showMessageDialog(this, "Please Enter Valid Date!");
            }
            else{
                
                try{
                    int empID=Integer.parseInt(jTextField_empID.getText());
                    empSalaryList=db_crud.readEmployeeSalaryDB(empID);
                    List<EmployeeInformation> employeeInformations=db_crud.readAllDB();
                    if(empSalaryList.isEmpty()){
                        JOptionPane.showMessageDialog(this, "Salary for Employee ID: "+empID+" Not Found!");
                    }
                    else if(employeeInformations.isEmpty()){
                        JOptionPane.showMessageDialog(this, "Employees' Informations Not Found! ");
                    }
                    else{
                       // DefaultTableModel model=(DefaultTableModel) jTable1.getModel();
                        Object rowData[]=new Object[15];
                        for(EmployeeSalary e:empSalaryList){
                            int emp_index=searchList(employeeInformations,0,employeeInformations.size(), e.getEmployeeId());
                            if(emp_index!=-1){ // if employee whose salary generated is found
                                rowData[0]=e.getEmployeeId();
                                rowData[1]=employeeInformations.get(emp_index).getEmployeeName();
                                rowData[2]=e.getSalaryDate();
                                rowData[3]=employeeInformations.get(emp_index).getGrossSalary();
                                rowData[4]=e.getWorkTime();
                                rowData[5]=e.getEarnedSalary();
                                rowData[6]=employeeInformations.get(emp_index).getPFund();
                                rowData[7]=employeeInformations.get(emp_index).getItax();
                                rowData[8]=employeeInformations.get(emp_index).getAdvSalary();
                                rowData[9]=employeeInformations.get(emp_index).getPFLoan();
                                rowData[10]=employeeInformations.get(emp_index).getPersonalLoan();
                                rowData[11]=employeeInformations.get(emp_index).getMessDed();
                                rowData[12]=employeeInformations.get(emp_index).getEOBI();
                                rowData[13]=employeeInformations.get(emp_index).getOtherDed();
                                rowData[14]=e.getNetSalary();
                                model.addRow(rowData);
                                
                            }
                        }
                    }
                }
                catch(NumberFormatException e){
                   JOptionPane.showMessageDialog(this, "Please Enter Valid Employee ID!");
                }
            }
        }
    }//GEN-LAST:event_jTextField_empIDKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Emp_Salary_Table.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Emp_Salary_Table.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Emp_Salary_Table.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Emp_Salary_Table.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Emp_Salary_Table().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBackButton;
    private javax.swing.JButton jButton_generateExcel;
    private javax.swing.JButton jButton_print;
    private javax.swing.JButton jButton_saveEditedInfo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabel_close;
    private javax.swing.JLabel jLabel_minimize;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField_editAdvSal;
    private javax.swing.JTextField jTextField_editEOBI;
    private javax.swing.JTextField jTextField_editItax;
    private javax.swing.JTextField jTextField_editMessDed;
    private javax.swing.JTextField jTextField_editOtherDed;
    private javax.swing.JTextField jTextField_editPFloan;
    private javax.swing.JTextField jTextField_editPersLoan;
    private javax.swing.JTextField jTextField_editPfund;
    private javax.swing.JTextField jTextField_empID;
    // End of variables declaration//GEN-END:variables
}
