/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package payroll;

import java.awt.Color;
import java.awt.event.KeyEvent;
import javax.swing.BorderFactory;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.border.Border;

/**
 *
 * @author mzohaib
 */
public class EmployeeViewFrame extends javax.swing.JFrame {

    /**
     * Creates new form EmployeeViewFrame
     */
    
    DB_CRUD db_crud;
    public EmployeeViewFrame() {
        initComponents();
        db_crud=DB_CRUD.getInstance();
        setTitle("Employee Information");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jEditorPane1 = new javax.swing.JEditorPane();
        jButton_save1 = new javax.swing.JButton();
        jTextField_Name7 = new javax.swing.JTextField();
        jTextField_Name12 = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jTextField_Shift = new javax.swing.JTextField();
        jTextField_ID = new javax.swing.JTextField();
        jTextField_hireDate = new javax.swing.JTextField();
        jTextField_Dept = new javax.swing.JTextField();
        jTextField_PC = new javax.swing.JTextField();
        jTextField_grossSalary = new javax.swing.JTextField();
        jTextField_basicSalary = new javax.swing.JTextField();
        jTextField_rentAllow = new javax.swing.JTextField();
        jTextField_medAllow = new javax.swing.JTextField();
        jTextField_Name = new javax.swing.JTextField();
        jTextField_convAllow = new javax.swing.JTextField();
        jTextField_AdvSalary = new javax.swing.JTextField();
        jTextField_FatherName = new javax.swing.JTextField();
        jTextField_CNIC = new javax.swing.JTextField();
        jTextField_Pfund = new javax.swing.JTextField();
        jTextField_Itax = new javax.swing.JTextField();
        jTextField_PfLoan = new javax.swing.JTextField();
        jTextField_PersonalLoan = new javax.swing.JTextField();
        jTextField_MessDed = new javax.swing.JTextField();
        jTextField_ResignDate = new javax.swing.JTextField();
        jTextField_EOBI = new javax.swing.JTextField();
        jTextField_OtherDed = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jBackButton = new javax.swing.JButton();
        jButton_add = new javax.swing.JButton();
        jButton_view = new javax.swing.JButton();
        jButton_saveData = new javax.swing.JButton();
        jLabel_close = new javax.swing.JLabel();
        jLabel_minimize = new javax.swing.JLabel();

        jLabel4.setText("ID");

        jScrollPane1.setViewportView(jEditorPane1);

        jButton_save1.setBackground(new java.awt.Color(204, 204, 204));
        jButton_save1.setFont(new java.awt.Font("Lucida Grande", 0, 16)); // NOI18N
        jButton_save1.setText("Save");
        jButton_save1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton_save1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton_save1MouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton_save1MouseEntered(evt);
            }
        });
        jButton_save1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_save1ActionPerformed(evt);
            }
        });

        jTextField_Name7.setFont(new java.awt.Font("Lucida Grande", 0, 16)); // NOI18N
        jTextField_Name7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_Name7ActionPerformed(evt);
            }
        });

        jTextField_Name12.setFont(new java.awt.Font("Lucida Grande", 0, 16)); // NOI18N
        jTextField_Name12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_Name12ActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 153, 255));

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 0, 16)); // NOI18N
        jLabel1.setText("Name");

        jLabel2.setFont(new java.awt.Font("Lucida Grande", 0, 16)); // NOI18N
        jLabel2.setText("ID");

        jLabel5.setFont(new java.awt.Font("Lucida Grande", 0, 16)); // NOI18N
        jLabel5.setText("Hire Date");

        jLabel6.setFont(new java.awt.Font("Lucida Grande", 0, 16)); // NOI18N
        jLabel6.setText("Department");

        jLabel7.setFont(new java.awt.Font("Lucida Grande", 0, 16)); // NOI18N
        jLabel7.setText("P.C");

        jLabel8.setFont(new java.awt.Font("Lucida Grande", 0, 16)); // NOI18N
        jLabel8.setText("Shift");

        jLabel9.setFont(new java.awt.Font("Lucida Grande", 0, 16)); // NOI18N
        jLabel9.setText("Gross Salary");

        jLabel10.setFont(new java.awt.Font("Lucida Grande", 0, 16)); // NOI18N
        jLabel10.setText("Basic Salary");

        jLabel11.setFont(new java.awt.Font("Lucida Grande", 0, 16)); // NOI18N
        jLabel11.setText("H.Rent Allowance");

        jLabel12.setFont(new java.awt.Font("Lucida Grande", 0, 16)); // NOI18N
        jLabel12.setText("Medical Allowance");

        jLabel13.setFont(new java.awt.Font("Lucida Grande", 0, 16)); // NOI18N
        jLabel13.setText("Conv Allowance");

        jTextField_Shift.setFont(new java.awt.Font("Lucida Grande", 0, 16)); // NOI18N
        jTextField_Shift.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_ShiftActionPerformed(evt);
            }
        });

        jTextField_ID.setFont(new java.awt.Font("Lucida Grande", 0, 16)); // NOI18N
        jTextField_ID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_IDActionPerformed(evt);
            }
        });
        jTextField_ID.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField_IDKeyPressed(evt);
            }
        });

        jTextField_hireDate.setFont(new java.awt.Font("Lucida Grande", 0, 16)); // NOI18N
        jTextField_hireDate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_hireDateActionPerformed(evt);
            }
        });

        jTextField_Dept.setFont(new java.awt.Font("Lucida Grande", 0, 16)); // NOI18N
        jTextField_Dept.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_DeptActionPerformed(evt);
            }
        });

        jTextField_PC.setFont(new java.awt.Font("Lucida Grande", 0, 16)); // NOI18N
        jTextField_PC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_PCActionPerformed(evt);
            }
        });

        jTextField_grossSalary.setFont(new java.awt.Font("Lucida Grande", 0, 16)); // NOI18N
        jTextField_grossSalary.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_grossSalaryActionPerformed(evt);
            }
        });

        jTextField_basicSalary.setFont(new java.awt.Font("Lucida Grande", 0, 16)); // NOI18N
        jTextField_basicSalary.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_basicSalaryActionPerformed(evt);
            }
        });

        jTextField_rentAllow.setFont(new java.awt.Font("Lucida Grande", 0, 16)); // NOI18N
        jTextField_rentAllow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_rentAllowActionPerformed(evt);
            }
        });

        jTextField_medAllow.setFont(new java.awt.Font("Lucida Grande", 0, 16)); // NOI18N
        jTextField_medAllow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_medAllowActionPerformed(evt);
            }
        });

        jTextField_Name.setFont(new java.awt.Font("Lucida Grande", 0, 16)); // NOI18N
        jTextField_Name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_NameActionPerformed(evt);
            }
        });

        jTextField_convAllow.setFont(new java.awt.Font("Lucida Grande", 0, 16)); // NOI18N
        jTextField_convAllow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_convAllowActionPerformed(evt);
            }
        });

        jTextField_AdvSalary.setFont(new java.awt.Font("Lucida Grande", 0, 16)); // NOI18N
        jTextField_AdvSalary.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_AdvSalaryActionPerformed(evt);
            }
        });

        jTextField_FatherName.setFont(new java.awt.Font("Lucida Grande", 0, 16)); // NOI18N
        jTextField_FatherName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_FatherNameActionPerformed(evt);
            }
        });

        jTextField_CNIC.setFont(new java.awt.Font("Lucida Grande", 0, 16)); // NOI18N
        jTextField_CNIC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_CNICActionPerformed(evt);
            }
        });

        jTextField_Pfund.setFont(new java.awt.Font("Lucida Grande", 0, 16)); // NOI18N
        jTextField_Pfund.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_PfundActionPerformed(evt);
            }
        });

        jTextField_Itax.setFont(new java.awt.Font("Lucida Grande", 0, 16)); // NOI18N
        jTextField_Itax.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_ItaxActionPerformed(evt);
            }
        });

        jTextField_PfLoan.setFont(new java.awt.Font("Lucida Grande", 0, 16)); // NOI18N
        jTextField_PfLoan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_PfLoanActionPerformed(evt);
            }
        });

        jTextField_PersonalLoan.setFont(new java.awt.Font("Lucida Grande", 0, 16)); // NOI18N
        jTextField_PersonalLoan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_PersonalLoanActionPerformed(evt);
            }
        });

        jTextField_MessDed.setFont(new java.awt.Font("Lucida Grande", 0, 16)); // NOI18N
        jTextField_MessDed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_MessDedActionPerformed(evt);
            }
        });

        jTextField_ResignDate.setFont(new java.awt.Font("Lucida Grande", 0, 16)); // NOI18N
        jTextField_ResignDate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_ResignDateActionPerformed(evt);
            }
        });

        jTextField_EOBI.setFont(new java.awt.Font("Lucida Grande", 0, 16)); // NOI18N
        jTextField_EOBI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_EOBIActionPerformed(evt);
            }
        });

        jTextField_OtherDed.setFont(new java.awt.Font("Lucida Grande", 0, 16)); // NOI18N

        jLabel15.setFont(new java.awt.Font("Lucida Grande", 0, 16)); // NOI18N
        jLabel15.setText("CNIC");

        jLabel16.setFont(new java.awt.Font("Lucida Grande", 0, 16)); // NOI18N
        jLabel16.setText("Resign Date");

        jLabel17.setFont(new java.awt.Font("Lucida Grande", 0, 16)); // NOI18N
        jLabel17.setText("Father Name");

        jLabel18.setFont(new java.awt.Font("Lucida Grande", 0, 16)); // NOI18N
        jLabel18.setText("P-Fund");

        jLabel19.setFont(new java.awt.Font("Lucida Grande", 0, 16)); // NOI18N
        jLabel19.setText("Income Tax");

        jLabel20.setFont(new java.awt.Font("Lucida Grande", 0, 16)); // NOI18N
        jLabel20.setText("PF Loan");

        jLabel21.setFont(new java.awt.Font("Lucida Grande", 0, 16)); // NOI18N
        jLabel21.setText("Personal Loan");

        jLabel22.setFont(new java.awt.Font("Lucida Grande", 0, 16)); // NOI18N
        jLabel22.setText("Advance Salary");

        jLabel23.setFont(new java.awt.Font("Lucida Grande", 0, 16)); // NOI18N
        jLabel23.setText("Other Ded");

        jLabel24.setFont(new java.awt.Font("Lucida Grande", 0, 16)); // NOI18N
        jLabel24.setText("EOBI");

        jLabel25.setFont(new java.awt.Font("Lucida Grande", 0, 16)); // NOI18N
        jLabel25.setText("Mess Deductions");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10)
                            .addComponent(jLabel11)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(13, 13, 13)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField_ID, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField_Shift, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField_PC, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField_Dept, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField_hireDate, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField_Name, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField_grossSalary, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField_basicSalary, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField_rentAllow, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 113, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel20)
                                        .addGap(72, 72, 72))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel22)
                                            .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(42, 42, 42)))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextField_AdvSalary, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextField_PfLoan, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel25))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTextField_PersonalLoan, javax.swing.GroupLayout.DEFAULT_SIZE, 350, Short.MAX_VALUE)
                                    .addComponent(jTextField_MessDed)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel15)
                                .addGap(79, 79, 79)
                                .addComponent(jTextField_CNIC, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jTextField_Itax, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jTextField_ResignDate, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jTextField_Pfund, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(32, 32, 32)
                                    .addComponent(jTextField_FatherName, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12)
                            .addComponent(jLabel13))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField_convAllow, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField_medAllow, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel24, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel23, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextField_OtherDed, javax.swing.GroupLayout.DEFAULT_SIZE, 351, Short.MAX_VALUE)
                            .addComponent(jTextField_EOBI)))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField_ID, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_CNIC, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField_Name, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTextField_FatherName, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jTextField_hireDate, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_ResignDate, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField_Dept, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_Pfund, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField_PC, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_Itax, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField_Shift, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_AdvSalary, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextField_grossSalary, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel9))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextField_PfLoan, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel10)
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField_PersonalLoan, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField_basicSalary, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField_MessDed, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField_rentAllow, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jTextField_medAllow, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel12)
                                    .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jTextField_convAllow, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel13)
                                    .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextField_OtherDed, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 50, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextField_EOBI, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
        );

        jLabel3.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        jLabel3.setText("EMPLOYEE INFORMATION");

        jLabel14.setForeground(new java.awt.Color(102, 102, 255));
        jLabel14.setText("Developed By Mohammad Zohaib Abbas ");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(139, 139, 139)
                .addComponent(jLabel14)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(110, Short.MAX_VALUE)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 341, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(59, 59, 59))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel14)
                .addGap(13, 13, 13))
        );

        jBackButton.setBackground(new java.awt.Color(204, 204, 204));
        jBackButton.setForeground(new java.awt.Color(102, 102, 255));
        jBackButton.setText("Back");
        jBackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBackButtonActionPerformed(evt);
            }
        });

        jButton_add.setText("ADD");
        jButton_add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_addActionPerformed(evt);
            }
        });

        jButton_view.setText("VIEW");
        jButton_view.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_viewActionPerformed(evt);
            }
        });

        jButton_saveData.setForeground(new java.awt.Color(102, 102, 255));
        jButton_saveData.setText("SAVE");
        jButton_saveData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_saveDataActionPerformed(evt);
            }
        });

        jLabel_close.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabel_close.setText(" X");
        jLabel_close.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel_close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_closeMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel_closeMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel_closeMouseEntered(evt);
            }
        });

        jLabel_minimize.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabel_minimize.setText(" -");
        jLabel_minimize.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel_minimize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_minimizeMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel_minimizeMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel_minimizeMouseEntered(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(87, 87, 87)
                        .addComponent(jButton_add, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton_view, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton_saveData, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jBackButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(203, 203, 203)
                        .addComponent(jLabel_minimize, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel_close, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel_close)
                                .addComponent(jLabel_minimize))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jBackButton)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton_saveData)
                            .addComponent(jButton_view)
                            .addComponent(jButton_add))
                        .addGap(2, 2, 2)))
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel_minimizeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_minimizeMouseClicked
        this.setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_jLabel_minimizeMouseClicked

    private void jLabel_minimizeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_minimizeMouseExited
        Border label_border=BorderFactory.createMatteBorder(1,1,1,1, Color.black);
        jLabel_minimize.setBorder(label_border);
        jLabel_minimize.setForeground(Color.black);
    }//GEN-LAST:event_jLabel_minimizeMouseExited

    private void jLabel_minimizeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_minimizeMouseEntered
        Border label_border=BorderFactory.createMatteBorder(1,1,1,1, Color.white);
        jLabel_minimize.setBorder(label_border);
        jLabel_minimize.setForeground(Color.white);
    }//GEN-LAST:event_jLabel_minimizeMouseEntered

    private void jLabel_closeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_closeMouseClicked
        System.exit(0);
    }//GEN-LAST:event_jLabel_closeMouseClicked

    private void jLabel_closeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_closeMouseExited
        Border label_border=BorderFactory.createMatteBorder(1,1,1,1, Color.black);
        jLabel_close.setBorder(label_border);
        jLabel_close.setForeground(Color.black);
    }//GEN-LAST:event_jLabel_closeMouseExited

    private void jLabel_closeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_closeMouseEntered
        Border label_border=BorderFactory.createMatteBorder(1,1,1,1, Color.white);
        jLabel_close.setBorder(label_border);
        jLabel_close.setForeground(Color.white);
    }//GEN-LAST:event_jLabel_closeMouseEntered

    private void jTextField_ShiftActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_ShiftActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_ShiftActionPerformed

    private void jTextField_IDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_IDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_IDActionPerformed

    private void jTextField_hireDateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_hireDateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_hireDateActionPerformed

    private void jTextField_DeptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_DeptActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_DeptActionPerformed

    private void jTextField_PCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_PCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_PCActionPerformed

    private void jTextField_grossSalaryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_grossSalaryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_grossSalaryActionPerformed

    private void jTextField_basicSalaryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_basicSalaryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_basicSalaryActionPerformed

    private void jTextField_rentAllowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_rentAllowActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_rentAllowActionPerformed

    private void jTextField_medAllowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_medAllowActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_medAllowActionPerformed

    private void jTextField_NameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_NameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_NameActionPerformed

    private void jTextField_convAllowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_convAllowActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_convAllowActionPerformed

    private void jButton_save1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_save1MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton_save1MouseExited

    private void jButton_save1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_save1MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton_save1MouseEntered

    private void jButton_save1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_save1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton_save1ActionPerformed

    private void jTextField_IDKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_IDKeyPressed
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            if(jTextField_ID.getText().equals("")||jTextField_ID.getText().equals(" ")||jTextField_ID.getText()==null){
             JOptionPane.showMessageDialog(this, "Please Enter Valid ID!");
            }
            else{
                try{
                EmployeeInformation e=db_crud.searchDB(Integer.parseInt(jTextField_ID.getText()));
                if(e!=null){ 
                    jTextField_Name.setText(e.getEmployeeName());
                    jTextField_hireDate.setText(e.gethireDate());
                    jTextField_Dept.setText(e.getDeptName());
                    jTextField_PC.setText(e.getPC());
                    jTextField_Shift.setText(e.getShift());
                    jTextField_grossSalary.setText(String.valueOf(e.getGrossSalary()));
                    jTextField_basicSalary.setText(String.valueOf(e.getBasicSalary()));
                    jTextField_rentAllow.setText(String.valueOf(e.getRentAllow()));
                    jTextField_medAllow.setText(String.valueOf(e.getMedAllow()));
                    jTextField_convAllow.setText(String.valueOf(e.getConvAllow()));
                    jTextField_CNIC.setText(String.valueOf(e.getCNIC()));
                    jTextField_FatherName.setText(String.valueOf(e.getFatherName()));
                    jTextField_ResignDate.setText(String.valueOf(e.getResignDate()));
                    jTextField_Pfund.setText(String.valueOf(e.getPFund()));
                    jTextField_Itax.setText(String.valueOf(e.getItax()));
                    jTextField_AdvSalary.setText(String.valueOf(e.getAdvSalary()));
                    jTextField_PfLoan.setText(String.valueOf(e.getPFLoan()));
                    jTextField_PersonalLoan.setText(String.valueOf(e.getPersonalLoan()));
                    jTextField_MessDed.setText(String.valueOf(e.getMessDed()));
                    jTextField_EOBI.setText(String.valueOf(e.getEOBI()));
                    jTextField_OtherDed.setText(String.valueOf(e.getOtherDed()));
                    
                }
                else{
                    jTextField_Name.setText("");
                    jTextField_hireDate.setText("");
                    jTextField_Dept.setText("");
                    jTextField_PC.setText("");
                    jTextField_Shift.setText("");
                    jTextField_grossSalary.setText("");
                    jTextField_basicSalary.setText("");
                    jTextField_rentAllow.setText("");
                    jTextField_medAllow.setText("");
                    jTextField_convAllow.setText("");
                    jTextField_CNIC.setText("");
                    jTextField_FatherName.setText("");
                    jTextField_ResignDate.setText("");
                    jTextField_Pfund.setText("");
                    jTextField_Itax.setText("");
                    jTextField_AdvSalary.setText("");
                    jTextField_PfLoan.setText("");
                    jTextField_PersonalLoan.setText("");
                    jTextField_MessDed.setText("");
                    jTextField_EOBI.setText("");
                    jTextField_OtherDed.setText("");
                    JOptionPane.showMessageDialog(this, "Employee Not Found in Database!");
                }
               } catch(Exception e){
                   JOptionPane.showMessageDialog(this, "Please Enter Valid ID!");
                 }
              }
            
         }
    }//GEN-LAST:event_jTextField_IDKeyPressed

    private void jBackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBackButtonActionPerformed
        this.setVisible(false);
        Payroll.getHomePage().setVisible(true);
    }//GEN-LAST:event_jBackButtonActionPerformed

    private void jTextField_AdvSalaryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_AdvSalaryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_AdvSalaryActionPerformed

    private void jTextField_FatherNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_FatherNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_FatherNameActionPerformed

    private void jTextField_CNICActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_CNICActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_CNICActionPerformed

    private void jTextField_PfundActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_PfundActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_PfundActionPerformed

    private void jTextField_ItaxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_ItaxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_ItaxActionPerformed

    private void jTextField_PfLoanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_PfLoanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_PfLoanActionPerformed

    private void jTextField_Name7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_Name7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_Name7ActionPerformed

    private void jTextField_PersonalLoanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_PersonalLoanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_PersonalLoanActionPerformed

    private void jTextField_MessDedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_MessDedActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_MessDedActionPerformed

    private void jTextField_ResignDateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_ResignDateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_ResignDateActionPerformed

    private void jTextField_EOBIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_EOBIActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_EOBIActionPerformed

    private void jTextField_Name12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_Name12ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_Name12ActionPerformed

    private void jButton_saveDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_saveDataActionPerformed
        EmployeeInformation e=null;
        try{
            int id=Integer.parseInt(jTextField_ID.getText());
            e=db_crud.searchDB(Integer.parseInt(jTextField_ID.getText()));
            
            if(e!=null){
            int opt= JOptionPane.showConfirmDialog(this,"Are you sure you want to save the changes?","Save",JOptionPane.YES_NO_OPTION);
            if(opt==0){ // if Yes
                e.setEmployeeName(jTextField_Name.getText());
                e.sethireDate(jTextField_hireDate.getText());
                e.setDeptName(jTextField_Dept.getText());
                e.setPC(jTextField_PC.getText());
                e.setShift(jTextField_Shift.getText());
                e.setCnic(jTextField_CNIC.getText());
                e.setFatherName(jTextField_FatherName.getText());
                e.setResignDate(jTextField_ResignDate.getText());
                
                e.setP_Fund(Integer.parseInt(jTextField_Pfund.getText()));
                e.setItax(Integer.parseInt(jTextField_Itax.getText()));
                e.setAdvSal(Integer.parseInt(jTextField_AdvSalary.getText()));
                e.setPF_Loan(Integer.parseInt(jTextField_PfLoan.getText()));
                e.setPersonalLoan(Integer.parseInt(jTextField_PersonalLoan.getText()));
                e.setMessDed(Integer.parseInt(jTextField_MessDed.getText()));
                e.setEOBI(Integer.parseInt(jTextField_EOBI.getText()));
                e.setOtherDed(Integer.parseInt(jTextField_OtherDed.getText()));
                e.setGrossSalary(Integer.parseInt(jTextField_grossSalary.getText()));
                e.setBasicSalary(Integer.parseInt(jTextField_basicSalary.getText()));
                e.setRentAllow(Integer.parseInt(jTextField_rentAllow.getText()));
                e.setMedAllow(Integer.parseInt(jTextField_medAllow.getText()));
                e.setConvAllow(Integer.parseInt(jTextField_convAllow.getText()));
                
                boolean flag=db_crud.updateDB(e);
                if(flag){
                    JOptionPane.showMessageDialog(this, "Employee Information Updated Successfully!");
                }
                else{
                    JOptionPane.showMessageDialog(this, "Update Failed!");
                }
                
                }
            }
            
            else{ // If trying to add a new employee in the database
            boolean flag=false;
            int new_emp_id=0,new_emp_grossSal=0,new_emp_basicSal=0,new_emp_rentAllow=0,new_emp_medAllow=0,new_emp_convAllow=0,new_emp_pfund=0,new_emp_itax=0,new_emp_aSal=0,new_emp_pfLoan=0,new_emp_persLoan=0,new_emp_mess=0,new_emp_eobi=0,new_emp_other=0;
            
            String new_emp_name=jTextField_Name.getText();
            String new_emp_hire_date=jTextField_hireDate.getText();
            String new_emp_dept=jTextField_Dept.getText();
            String new_emp_PC=jTextField_PC.getText();
            String new_emp_shift=jTextField_Shift.getText();
            String new_emp_cnic=jTextField_CNIC.getText();
            String new_emp_fname=jTextField_FatherName.getText();
            String new_emp_ResignDate=jTextField_ResignDate.getText();

            if(new_emp_ResignDate.trim().length()==0){
                new_emp_ResignDate="Not Available";
            }

            if(new_emp_name.trim().length()==0||new_emp_hire_date.trim().length()==0||new_emp_dept.trim().length()==0||new_emp_PC.trim().length()==0||new_emp_shift.trim().length()==0||new_emp_cnic.trim().length()==0||new_emp_fname.trim().length()==0){
                JOptionPane.showMessageDialog(this, "Please Fill All Non-Empty Fields!");
            }
            else{
                try{
                    new_emp_id=Integer.parseInt(jTextField_ID.getText());
                    new_emp_grossSal=Integer.parseInt(jTextField_grossSalary.getText());
                    new_emp_basicSal=Integer.parseInt(jTextField_basicSalary.getText());
                    new_emp_rentAllow=Integer.parseInt(jTextField_rentAllow.getText());
                    new_emp_medAllow=Integer.parseInt(jTextField_medAllow.getText());
                    new_emp_convAllow=Integer.parseInt(jTextField_convAllow.getText());
                    
                    new_emp_pfund=Integer.parseInt(jTextField_Pfund.getText());
                    new_emp_itax=Integer.parseInt(jTextField_Itax.getText());
                    new_emp_aSal=Integer.parseInt(jTextField_AdvSalary.getText());
                    new_emp_pfLoan=Integer.parseInt(jTextField_PfLoan.getText());
                    new_emp_persLoan=Integer.parseInt(jTextField_PersonalLoan.getText());
                    new_emp_mess=Integer.parseInt(jTextField_MessDed.getText());
                    new_emp_eobi=Integer.parseInt(jTextField_EOBI.getText());
                    new_emp_other=Integer.parseInt(jTextField_OtherDed.getText());
                }
                catch(NumberFormatException numberFormatException){
                    JOptionPane.showMessageDialog(this, "Enter Only Numeric Values for Salary and Deduction Fields!");
                    flag=true;
                }
            }
            if(!flag){
                EmployeeInformation new_emp=new EmployeeInformation(new_emp_id,new_emp_name,new_emp_hire_date,new_emp_grossSal,new_emp_dept,new_emp_PC,new_emp_shift,new_emp_basicSal,new_emp_rentAllow,new_emp_medAllow,new_emp_convAllow);
                new_emp.setCnic(new_emp_cnic);
                new_emp.setFatherName(new_emp_fname);
                new_emp.setResignDate(new_emp_ResignDate);
                new_emp.setP_Fund(new_emp_pfund);
                new_emp.setItax(new_emp_itax);
                new_emp.setAdvSal(new_emp_aSal);
                new_emp.setPF_Loan(new_emp_pfLoan);
                new_emp.setPersonalLoan(new_emp_persLoan);
                new_emp.setMessDed(new_emp_mess);
                new_emp.setEOBI(new_emp_eobi);
                new_emp.setOtherDed(new_emp_other);

                boolean check=db_crud.insertSingleEmployeeInDB(new_emp);
                if(check){
                    JOptionPane.showMessageDialog(this, "New Employee Saved Successfully!");
                }
                else{
                    JOptionPane.showMessageDialog(this, "New Employee NOT Saved Successfully!");
                }
            }

        }
                
        }
        catch(NumberFormatException ne){
            JOptionPane.showMessageDialog(this, "Please Enter Valid ID!");
            e=null;
        }
               
    }//GEN-LAST:event_jButton_saveDataActionPerformed

    private void jButton_addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_addActionPerformed

                    jTextField_ID.setText("");
                    jTextField_Name.setText("");
                    jTextField_hireDate.setText("");
                    jTextField_Dept.setText("");
                    jTextField_PC.setText("");
                    jTextField_Shift.setText("");
                    jTextField_grossSalary.setText("");
                    jTextField_basicSalary.setText("");
                    jTextField_rentAllow.setText("");
                    jTextField_medAllow.setText("");
                    jTextField_convAllow.setText("");
                    jTextField_CNIC.setText("");
                    jTextField_FatherName.setText("");
                    jTextField_ResignDate.setText("");
                    jTextField_Pfund.setText("");
                    jTextField_Itax.setText("");
                    jTextField_AdvSalary.setText("");
                    jTextField_PfLoan.setText("");
                    jTextField_PersonalLoan.setText("");
                    jTextField_MessDed.setText("");
                    jTextField_EOBI.setText("");
                    jTextField_OtherDed.setText("");
                    JOptionPane.showMessageDialog(this, "Please Fill The Form Now And Press Save button!");
    }//GEN-LAST:event_jButton_addActionPerformed

    private void jButton_viewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_viewActionPerformed

            try{
                EmployeeInformation e=db_crud.searchDB(Integer.parseInt(jTextField_ID.getText()));
                if(e!=null){ 
                    jTextField_Name.setText(e.getEmployeeName());
                    jTextField_hireDate.setText(e.gethireDate());
                    jTextField_Dept.setText(e.getDeptName());
                    jTextField_PC.setText(e.getPC());
                    jTextField_Shift.setText(e.getShift());
                    jTextField_grossSalary.setText(String.valueOf(e.getGrossSalary()));
                    jTextField_basicSalary.setText(String.valueOf(e.getBasicSalary()));
                    jTextField_rentAllow.setText(String.valueOf(e.getRentAllow()));
                    jTextField_medAllow.setText(String.valueOf(e.getMedAllow()));
                    jTextField_convAllow.setText(String.valueOf(e.getConvAllow()));
                    jTextField_CNIC.setText(String.valueOf(e.getCNIC()));
                    jTextField_FatherName.setText(String.valueOf(e.getFatherName()));
                    jTextField_ResignDate.setText(String.valueOf(e.getResignDate()));
                    jTextField_Pfund.setText(String.valueOf(e.getPFund()));
                    jTextField_Itax.setText(String.valueOf(e.getItax()));
                    jTextField_AdvSalary.setText(String.valueOf(e.getAdvSalary()));
                    jTextField_PfLoan.setText(String.valueOf(e.getPFLoan()));
                    jTextField_PersonalLoan.setText(String.valueOf(e.getPersonalLoan()));
                    jTextField_MessDed.setText(String.valueOf(e.getMessDed()));
                    jTextField_EOBI.setText(String.valueOf(e.getEOBI()));
                    jTextField_OtherDed.setText(String.valueOf(e.getOtherDed()));
                    
                }
                else{
                    jTextField_Name.setText("");
                    jTextField_hireDate.setText("");
                    jTextField_Dept.setText("");
                    jTextField_PC.setText("");
                    jTextField_Shift.setText("");
                    jTextField_grossSalary.setText("");
                    jTextField_basicSalary.setText("");
                    jTextField_rentAllow.setText("");
                    jTextField_medAllow.setText("");
                    jTextField_convAllow.setText("");
                    jTextField_CNIC.setText("");
                    jTextField_FatherName.setText("");
                    jTextField_ResignDate.setText("");
                    jTextField_Pfund.setText("");
                    jTextField_Itax.setText("");
                    jTextField_AdvSalary.setText("");
                    jTextField_PfLoan.setText("");
                    jTextField_PersonalLoan.setText("");
                    jTextField_MessDed.setText("");
                    jTextField_EOBI.setText("");
                    jTextField_OtherDed.setText("");
                    JOptionPane.showMessageDialog(this, "Employee Not Found in Database!");
                }
               } catch(NumberFormatException ne){
                   JOptionPane.showMessageDialog(this, "Please Enter Valid ID!");
                 }

    }//GEN-LAST:event_jButton_viewActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EmployeeViewFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EmployeeViewFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EmployeeViewFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EmployeeViewFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EmployeeViewFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBackButton;
    private javax.swing.JButton jButton_add;
    private javax.swing.JButton jButton_save1;
    private javax.swing.JButton jButton_saveData;
    private javax.swing.JButton jButton_view;
    private javax.swing.JEditorPane jEditorPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabel_close;
    private javax.swing.JLabel jLabel_minimize;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField_AdvSalary;
    private javax.swing.JTextField jTextField_CNIC;
    private javax.swing.JTextField jTextField_Dept;
    private javax.swing.JTextField jTextField_EOBI;
    private javax.swing.JTextField jTextField_FatherName;
    private javax.swing.JTextField jTextField_ID;
    private javax.swing.JTextField jTextField_Itax;
    private javax.swing.JTextField jTextField_MessDed;
    private javax.swing.JTextField jTextField_Name;
    private javax.swing.JTextField jTextField_Name12;
    private javax.swing.JTextField jTextField_Name7;
    private javax.swing.JTextField jTextField_OtherDed;
    private javax.swing.JTextField jTextField_PC;
    private javax.swing.JTextField jTextField_PersonalLoan;
    private javax.swing.JTextField jTextField_PfLoan;
    private javax.swing.JTextField jTextField_Pfund;
    private javax.swing.JTextField jTextField_ResignDate;
    private javax.swing.JTextField jTextField_Shift;
    private javax.swing.JTextField jTextField_basicSalary;
    private javax.swing.JTextField jTextField_convAllow;
    private javax.swing.JTextField jTextField_grossSalary;
    private javax.swing.JTextField jTextField_hireDate;
    private javax.swing.JTextField jTextField_medAllow;
    private javax.swing.JTextField jTextField_rentAllow;
    // End of variables declaration//GEN-END:variables
}
